services:
  # Service WordPress
  wordpress:
    image: wordpress:${WORDPRESS_VERSION}
    restart: always
    ports:
      - "${WORDPRESS_PORT}:80"  # Expose WordPress on port 8080
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress_data:/var/www/html  # Persist data for WordPress
